spring:
  application:
    name: department-service
  config:
    import: "optional:configserver:http://localhost:8088"
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/departmentdb
    password:
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      open-in-view: true
